eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8904
spring:
  application:
    name: service-zuul
  profiles:
    active: dev,hello
  data:
    redis:
      repositories:
        enabled: true
#  redis:
#    #url: jtzsw_redis@127.0.0.1:6379
#    url: 127.0.0.1:6379
#    database: 0
#    host: localhost
#    #password: jtzsw_redis
#    port: 6379
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      serviceId: ribbon-client
    feign:
      path: /api-feign/**
      serviceId: FeignClient